change-template: "* $TITLE (#$NUMBER) by @$AUTHOR"
inputs:
  tag_version:
    required: true
name-template: '$RESOLVED_VERSION'
tag: ${{ inputs.tag_version }}
template: |
  ## Summary

  ## Changes

  $CHANGES

  ## This release was made possible by the following contributors:

  $CONTRIBUTORS
