name: DEV Workflow
on:
  # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [develop]
#   pull_request:
#     branches: [develop]
  workflow_dispatch:
  

jobs: 
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: versioning with pubspec
        uses: NiklasLehnfeld/flutter-version-number-action@main
        with:
          file-path: ./pubspec.yaml
