name: tesing Workflow
on:
  # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [develop]
#   pull_request:
#     branches: [develop]
  workflow_dispatch:
  
permissions:
  contents: write

jobs: 
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: checout
        uses: actions/checkout@v2
#       - name: New Release Publish
#         uses: release-drafter/release-drafter@v5
#         with:
#           publish : true
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Get package version
        id: get_version
        run: echo "::set-output name=version::$(awk '/^version:/ {print $2}' pubspec.yaml)"

      - name: Create Git tag
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "rf-opssupport@kansocloud.com"
          git tag ${{ steps.get_version.outputs.version }}
          git push origin ${{ steps.get_version.outputs.version }}
