name: tesing Workflow
on:
  # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [develop]
#   pull_request:
#     branches: [develop]
  workflow_dispatch:
  
permissions:
  contents: write

jobs: 
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: checout
        uses: actions/checkout@v2
        
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Get package version
        id: get_version
        run: echo "::set-output name=version::$(awk '/^version:/ {print $2}' pubspec.yaml)"
      
      - name: check tag
        uses: mukunku/tag-exists-action@v1.2.0
        id: checkTag
        with: 
          tag: ${{ steps.get_version.outputs.version }}
          
#       - name: Check if tag exists
#         id: tag_exists
#         run: |
#           if git rev-parse -q --verify "refs/tags/${{ steps.get_version.outputs.version }}"; then
#             echo "::set-output name=exists::true"
#           else
#             echo "::set-output name=exists::false"
#           fi

      - name: Create Git tag
        if: ${{ steps.checkTag.outputs.exists == 'false' }}
        run: |
          git tag ${{ steps.get_version.outputs.version }}
          git push origin ${{ steps.get_version.outputs.version }}
